server:
  port: 8111

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: file:${syt.upload}

# 自定义上传文件配置 服务器上需要修改 第一个win  第二个 linux  第三个 mac
syt:
  #  upload: F:\upload\
#  upload: /root/upload
  upload: /Users/space/Downloads/qq_file

# ip 文件上传路径 下面是服务器ip
ip: 127.0.0.1
#ip: 111.229.170.213
#ip: 47.115.43.73